name: Testing PostgreSQL service-container
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest

    container: node:18

    services:
      postgres-test-service:
        image: postgres

        env:
          POSTGRES_PASSWORD: Tiadavino3

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download repository code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client and dockerize
        run: |
          apt-get update
          apt-get install -y postgresql-client
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          rm dockerize-linux-amd64-v0.6.1.tar.gz

      - name: Wait for PostgreSQL to be ready
        run: dockerize -wait tcp://postgres-test-service:5432 -timeout 1m

      - name: Create PostgreSQL database
        run: |
          export PGPASSWORD=$POSTGRES_PASSWORD
          psql -h postgres-test-service -U postgres -d postgres -c "CREATE DATABASE mytest"
          unset PGPASSWORD

      - name: Install All dependencies
        run: npm ci

      - name: Connect to PostgreSQL

        run: node client.js

        env:
          POSTGRES_HOST: postgres-test-service

          POSTGRES_PORT: 5432
